### ISSUE TITLE
Memory leaking when Loki server is down

### ISSUE THREAD

**Issue by DanielSanIT** [serilog-contrib/serilog-sinks-grafana-loki#119]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

м7.1.1

### Which version of .NET are you using?

net6.0

### Describe the bug

When Loki server is down, serilog taking lot of memory and not purging it.

### To Reproduce

Turn off Loki server.
Create many logs as you can.
Watch profiler.

### Expected behavior

I think that system should purge logs if there is no connection to Loki.
Or should keep controlled amount of logs to try to upload to Loki of server will appear.

Logging system should not crash host system relating to its problems.

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
Hello @DanielSanIT ,

The reason behind this behavior is described here https://github.com/serilog-contrib/serilog-sinks-grafana-loki/issues/90#issuecomment-1065023112

Agree, that is could be reasonable to control max amount of log in buffer. But it is important to have a behavior understanding - should we push out the older one, when new will arrive. Or should we just drop new, while buffer is full?

**Comment by mishamyte** [comment]
So, according to a doc, you could next parameters to adjust behavior more precisely:

- `batchPostingLimit ` - the maximum number of events to post in a single batch. Default value is 1000
-  `queueLimit ` - the maximum number of events stored in the queue in memory, waiting to be posted over the network. Default value is infinitely
- `period` - the time to wait between checking for event batches. Default value is 2 seconds
