### ISSUE TITLE
"Request Entity Too Large" and "dropped events" for large messages

### ISSUE THREAD

**Issue by object** [serilog-contrib/serilog-sinks-grafana-loki#146]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

v8.0.1

### Which version of .NET are you using?

net6.0

### Describe the bug

I was testing memory consumption for scenario with large messages. I see an increase of allocated memory for large messages but need to run a test app longer to draw any conclusion about memory leak. Using BenchmarkDotNet didn't expose any memory leaks so far.

However while settings log message size to 5000, I see both failures on HTTP shipping and dropped messages.

Here is the error message:

> Received failure on HTTP shipping (413): <html>
> <head><title>413 Request Entity Too Large</title></head>
> <body>
> <center><h1>413 Request Entity Too Large</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> . 123 log events will be dropped
> 

What is strange is that I don't see this error immediately on a first message that is logged. It comes during a round of 1000 messages. Perhaps they are batched and sent in a larger payload which causes overflow?

### To Reproduce

1. Generate messages of 5000 symbols
2. Enable Serilog.Debugging.SelfLog.Enable(Console.Error)
3. Start logging them (I logged them with 10ms interval)
4. Wait for an error to be printed

I have a sample app that I can submit if necessary, but it should be fairly easy to reproduce

### Expected behavior

Messages of 5000 bytes should be logged without errors

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
@object thank you!

Sounds interesting, will have a look.

I don't know if it will have a difference, but do you use self-hosted Loki/Grafana or cloud one?

**Comment by object** [comment]
Self hosted one.

**Comment by mishamyte** [comment]
I played a little with it. Created a simple console app. Used default params.

So what I've achieved.

Using next "spamming code":
```csharp
var logEntry = new string('0', 5000);

while (true)
{
    Log.Information("{Entry}", logEntry);
    await Task.Delay(10);
}

await Log.CloseAndFlushAsync();
```

No problems, about 64 log entry per second.

After removing `Task.Delay` the next error starts appearing in logs:
```
2022-10-15T20:36:10.1096096Z Received failure on HTTP shipping (429): Ingestion rate limit exceeded for user fake (limit: 4194304 bytes/sec) while attempting to ingest '1000' lines totaling '10072000' bytes, reduce log volume or contact your Loki administrator to see if the limit can be increased
. 1000 log events will be dropped
```

But it is related to Loki configuration and it's ingestion rate.

So I didn't observe any 413s here.

Any suggestions/code samples?

**Comment by object** [comment]
I created a gist with a sample program:
https://gist.github.com/object/b18da2cad9c2a51efd3cc774a19085d3

The part of the gist that does memory checks is not important. When I run this sample against our Loki server, I get something like this:

> Sending 1000 messages of 5000 chars
> 2022-10-16T08:40:52.4478042Z Received failure on HTTP shipping (413): <html>
> <head><title>413 Request Entity Too Large</title></head>
> <body>
> <center><h1>413 Request Entity Too Large</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> . 126 log events will be dropped
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Waiting for memory to be freed
> Total memory after GC = 862 KB
>

**Comment by mishamyte** [comment]
Nice, thanks. Will check with your example soon

**Comment by mishamyte** [comment]
Still no success.

Tried with my default instance in docker compose. 

Repeatedly launched your example on 1k, 2k, 5k messages.

Then added nginx before Loki and tried again.
Still can't reproduce it 😔

**Comment by mishamyte** [comment]
Maybe you could check Loki logs and find the error for its side while rejecting the payload?

We could try to find an info from that end

**Comment by object** [comment]
Okay, thank you for investigating. Then I suspect the issue may be caused by our Loki server rejecting larger messages either due to misconfiguration or something else. This is not your library concern indeed. It may however be that when 403 error occurs and some log entries get dropped, the allocated memory is not fully cleared. At least this is our observation. But if so this is another issue that I will report separatley if I reproduce it. I am closing this one for now.
