### ISSUE TITLE
System.Text.Json 7.0 really necessary? (Raises Warnings)

### ISSUE THREAD

**Issue by TsengSR** [serilog-contrib/serilog-sinks-grafana-loki#160]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

v8.1.0

### Which version of .NET are you using?

net5.0

### Describe the bug

Does the Sink **really** needs a dependency on `System.Text.Json` 7.0.0? For libraries it's generally favored to take the lowest versions which support the required features. 

Referencing `Serilog.Sinks.Grafana.Loki` in a `net5.0` (and probably also in `net6.0` gives some nasty and annoying warnings 

```
Warning		System.Text.Encodings.Web 7.0.0 doesn't support net5.0 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.	SomeProject	C:\Users\<Username>\.nuget\packages\system.text.encodings.web\7.0.0\buildTransitive\netcoreapp2.0\System.Text.Encodings.Web.targets	4	
```

even though it also targets `netstandard2.0`. 

### To Reproduce

Add `Serilog.Sinks.Grafana.Loki` to an empty `net5.0` project. 

### Expected behavior

Adding the Sink should not raise warnings.

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
Hi @TsengSR,

Thanks for your opinion.
Sounds reasonable, will think about it.

Also plan to drop "standard" from v9+ and set the explicit targets

**Comment by mishamyte** [comment]
Extracted to more global #171
