### ISSUE TITLE
OutOfMemoryException and missing log messages

### ISSUE THREAD

**Issue by steingran** [serilog-contrib/serilog-sinks-grafana-loki#170]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

v8.1.0

### Which version of .NET are you using?

.NET 7.0.4

### Describe the bug

Using this nuget in a .NET 7 microservice using Minimal API. The standard logging for HttpClient created via IHttpClientFactory is in place, which outputs a lot of messages like this:

![image](https://user-images.githubusercontent.com/22586339/230794493-9ddcf011-52e9-4831-bb23-381d1b22edea.png)

But when I query for messages that contain “Sending HTTP request GET“ in Loki, I do not find any instance of this text: "Sending HTTP request GET". Same thing with messages starting with "Start processing HTTP request GET", there are none of these in Loki either.

However, the shorter text “Received HTTP response headers after“ can be found in Loki.  Same thing with the “End processing HTTP request after“, the full text that is logged is “Received HTTP response headers after 36.1983ms - 200“ and “End processing HTTP request after 37.1225ms - 200“.

After running for some hours, we get an OutOfMemoryException. A memory snapshot shows the following objects in Generation 2 memory: 
![image](https://user-images.githubusercontent.com/22586339/230794613-501e5697-0d65-4057-a34d-637e58ba990a.png)

So a lot of logging-related objects are present: LokiLogEvent, LogEvent, LogEventPropertyValue, LogEventProperty

### To Reproduce

Create an ASP.NET Core project, using Minimal API. Add the Loki nuget, use IHttpClientFactory to create HttpClient instances, and keep the default logging for these HttpClient instances. Call external HTTP endpoints, and observe the memory usage increasing until an OutOfMemoryException occurs.

### Expected behavior

No memoy leak, and that all log entries are actually sent over to Loki

### Log/SelfLog output or exception with stacktrace

2023-03-30T17:45:44.2980609Z Exception while emitting periodic batch from Serilog.Sinks.Grafana.Loki.LokiSink: System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Serilog.Sinks.Grafana.Loki.HttpClients.LokiHttpClient.PostAsync(String requestUri, Stream contentStream) in /_/src/Serilog.Sinks.Grafana.Loki/HttpClients/LokiHttpClient.cs:line 36
   at Serilog.Sinks.Grafana.Loki.LokiSink.OnTick() in /_/src/Serilog.Sinks.Grafana.Loki/LokiSink.cs:line 120 

### Additional context

We tried removing the Loki nuget, and only used Serilog with Console logging. The OutOfMemoryExceptions then disappeared

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
Hi @steingran, 

So what I could suggest from SelfLog. Logs are not submitted (maybe partially according to your message) because of missconfiguration of `uri` and accumulate in memory (because your queue isn't restricted probably) until OOM happens.

Would love to see your configuration of the Sink (without the secrets, but `uri` is important here). If you would share it - I would have probably an ability to give you more detailed info

**Comment by steingran** [comment]
Hi @mishamyte, we configure the Loki logger sink in code:

`loggerConfiguration.WriteTo.GrafanaLoki(grafanaLokiUri,
                        labels: lokiLabels,
                        propertiesAsLabels: new string[] { "level" }
                    );`

Where 'grafanaLokiUri' is 'http://loki.monitoring.svc.cluster.local:3100', 'lokiLabels' is one label: app:servicename. Where 'servicename' can be 'ms-int' for instance.

So nothing extraordinary in the settings we use really. But how can a setting for the URI cause the logger sink to sometimes log to Loki and sometimes not?

**Comment by mishamyte** [comment]
> Hi @mishamyte, we configure the Loki logger sink in code:
> 
> `loggerConfiguration.WriteTo.GrafanaLoki(grafanaLokiUri,
>                         labels: lokiLabels,
>                         propertiesAsLabels: new string[] { "level" }
>                     );`
> 
> Where 'grafanaLokiUri' is 'http://loki.monitoring.svc.cluster.local:3100', 'lokiLabels' is one label: app:servicename. Where 'servicename' can be 'ms-int' for instance.
> 
> So nothing extraordinary in the settings we use really. But how can a setting for the URI cause the logger sink to sometimes log to Loki and sometimes not?

Seems correct. We have faced problems with incorrect configuration before, so I decided to double-check.

Will try to play with it a bit later, because interesting behavior

**Comment by mishamyte** [comment]
Hey @steingran!

Have you had a chance to play around with the problem?
