### ISSUE TITLE
Strugling pushing logs to a hosted Loki Instance

### ISSUE THREAD

**Issue by Triskae** [serilog-contrib/serilog-sinks-grafana-loki#245]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

V8

### Which version of .NET are you using?

net6.0

### Describe the bug

Hello, 

I'm struggling pushing logs to my cloud provider Loki instance.

I configured everything as state in the readme, but not succeeding with sending logs to Loki.
I managed to make it work with the cloud provider python example code [here](https://www.scaleway.com/en/docs/observability/cockpit/how-to/send-metrics-logs-to-cockpit/)

Do you support sending auth like this: `https://api_key:theapikeyhier@logs.cockpit.fr-par.scw.cloud` ? It seems not because, the `Serilog.Debugging.SelfLog.Enable(Console.Error);` is telling me that there's a 401 error.
Here is my code, do you see something wrong ?
```
public static IServiceCollection SetupSerilog(this IServiceCollection services, ConfigurationManager configuration)
    {
        var appLabel = new LokiLabel { Key = "Application", Value = "AppStaging" };
        var stagingLabel = new LokiLabel { Key = "Environment", Value = "Staging" };
        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Warning()
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .WriteTo.GrafanaLoki(
                "https://api_key:theapikey@logs.cockpit.fr-par.scw.cloud",
                new[] { appLabel, stagingLabel }, new[] { "Application", "Environment" })
            .Enrich.WithProperty("Application", "AppStaging")
            .Enrich.WithProperty("Environment", "Staging")
            .CreateLogger();

        return services;
    }
```

### To Reproduce

Configure a .NET 6 API to use Serilog and serilog-sinks-grafana-loki. Configure it with Scaleway way to auth.

### Expected behavior

To push logs as the python example.

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
Hi @Triskae,

Please, check #24, I believe it will be useful

**Comment by Triskae** [comment]
I spent all the afternoon digging this ... Working now, thanks a lot ! @mishamyte
