### ISSUE TITLE
LogLevel as label included

### ISSUE THREAD

**Issue by MeikelLP** [serilog-contrib/serilog-sinks-grafana-loki#35]
As recommended by the Loki team I try to use as few as possible labels. Sadly this library includes `level` although I'm not allowing it in the include:

```cs
new LoggerConfiguration()
    .ReadFrom.Configuration(configuration)
    .WriteTo.GrafanaLoki(lokiConfig.Uri,
        httpClient: new CustomHttpClient(lokiConfig),
        labels: new[]
        {
            new LokiLabel { Key = "Instance", Value = Environment.MachineName },
            new LokiLabel { Key = "Job", Value = lokiConfig.JobName }
        },
        textFormatter: new CompactJsonFormatter(),
        restrictedToMinimumLevel: configuration.GetValue<LogEventLevel>("Serilog:MinimumLevel:Default"),
        filtrationMode: LokiLabelFiltrationMode.Include,
        filtrationLabels: new[] { "Instance", "Job" })
    .CreateLogger();
```

Am I missing something or is this an actual bug?

**Comment by mishamyte** [comment]
Hello, @MeikelLP!

As it is mentioned [here](https://github.com/mishamyte/serilog-sinks-grafana-loki/issues/9#issuecomment-727531491).

```
This is a sink for logger, so I decided that it's reasonable to keep a log level as always present value. That behavior is designed
```

Also, I see that you are using JsonFormatter. So I could recommend look at [LokiJsonTextFormatter](https://github.com/mishamyte/serilog-sinks-grafana-loki/blob/master/src/Serilog.Sinks.Grafana.Loki/LokiJsonTextFormatter.cs), which does not generate level as label.

Also, I could offer a quick solution for case if a concrete formatter is required. Create a wrapper like [this](https://gist.github.com/mishamyte/17417ebd0be971c5a5e9b3ef78e67d81).


Also, just want to ask. How critical is to not a create level label? Is it comfortable to browse logs with Grafana without coloring levels?

**Comment by MeikelLP** [comment]
Hey, thanks for the quick answer.

I know log level labels are very beneficial. From what I read in the docs and heard in Loki talks I decided to test it without level for now. Maybe I add it later.

I will try the LokiJsonTextFormatter. For now this looked like a bug because I explicitly do not include level :)

**Comment by mishamyte** [comment]
As for me, `level` label is not a big deal, cause it is not a dynamic label (cause, there are only 6 possible variants of it's value (you could see it [here](https://github.com/mishamyte/serilog-sinks-grafana-loki/blob/master/src/Serilog.Sinks.Grafana.Loki/Utils/LogEventLevelExtensions.cs)).

It should be bug, if it was not implemented by design.

You are not the first one, who ask about this behavior, so I will create an action item for v7 milestone

**Comment by MeikelLP** [comment]
I see, I'm looking forward to it :)
