### ISSUE TITLE
How to parse TraceId from labels in grafana?

### ISSUE THREAD

**Issue by JumpAttacker** [serilog-contrib/serilog-sinks-grafana-loki#37]
Hey, im trying to use this feature
https://grafana.com/blog/2021/02/11/instrumenting-a-.net-web-api-using-opentelemetry-tempo-and-grafana-cloud/

but seems if traceId is not in log details it can't be parsed by grafana.

My question:
how to parse that value?

I need to add it to log details or there are another way to parse that value

my attemps
https://i.imgur.com/uqr5M9c.png

example of my log
https://i.imgur.com/3UL3IWL.png

json inside grafana loki
https://i.imgur.com/vBUX9P9.png

**Comment by mishamyte** [comment]
Hello, @JumpAttacker. 

I don't think it is the way how it should be done. 
The functionality of derived fields allows you to work with unstructured log and parse a fields from a row data. So the GraphQL language could be used for querying.

Serilog is structured logger, so the valuable fields are passed to the logger as LogEvent properties.
And this sink uses dat properties to pass it into Grafana as log labels, so you could use them for querying.

In your case you could just use a `{TraceId="value"}` way.

The given example shows the way how to do the same result with the raw data & derived fields feature.

**Comment by JumpAttacker** [comment]
Thanks, got it.

```
Also, I could suggest that the core of your questing is how to pass log's TraceId to Jaeger. Is it correct?
```
Yes, but I found that traceId from serilog is not the some that have jaeger, so dunno what is my next step

**Comment by mishamyte** [comment]
As I workaround, I could propose to add a TraceId into a MessageTemplate and parse it from the rendered message. But, honestly, I don't like this approach
