### ISSUE TITLE
make LokiJsonTextFormatter public

### ISSUE THREAD

**Issue by AndyPook** [serilog-contrib/serilog-sinks-grafana-loki#38]
`LokiJsonTextFormatter` is now `internal` in v6, which means that config in code via `UserSerilog` is broken 😢

**Comment by mishamyte** [comment]
Hi, @AndyPook!

Thank you for report.
Fixed in [v6.0.1](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/releases/tag/v6.0.1)
