### ISSUE TITLE
suffix is added to url but for cloud need clearly 

### ISSUE THREAD

**Issue by SergeyToff** [serilog-contrib/serilog-sinks-grafana-loki#40]
For example in documentation I need send :  https://user:apikey@logs-prod-us-central1.grafana.net/api/prom/push
Serilog do query - ...logs-prod-us-central1.grafana.net/loki/api/v1/push
or  - ...@logs-prod-us-central1.grafana.net/api/prom/push/loki/api/v1/push
if I try to insert full path
how can I change additional url without overriding http client in settings?

**Comment by mishamyte** [comment]
Pronto, @SergeyToff!

Seems like you need to setup work with proxy. Could [this](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/issues/24#issuecomment-813032147) solution help you?
