### ISSUE TITLE
Indexed placeholders in message template are translated to label keys that are not accepted by Loki

### ISSUE THREAD

**Issue by MaximPopov** [serilog-contrib/serilog-sinks-grafana-loki#45]
If a message template contains indexed placeholders (e.g. "Copy files from {0} to {1}") in string.Format() fashion, the code generates label keys for these parameters as numeric strings ("0" and "1", respectively).

Loki doesn't seem to accept such label keys. Version 2.3.0 returns BadRequest with the message "1:2: parse error: unexpected character inside braces: '0'" if there was a label with "0" key.

This becomes a problem if Serilog is plugged into a third-party library that uses this style of log message templates.

**Comment by MaximPopov** [comment]
Hi @mishamyte,

Commit 5e1cdccd9faa543d6436eab0cc0694a34b887ea2 on top of pull request #46 changes the key prefix from "param" to "Param-". Unfortunately, it turned out that Loki doesn't accept dash characters either. Now it's giving me BadRequest 1:82: parse error: unexpected character inside braces: '-'.

Could you please revert this single change so that the prefix doesn't include the dash?

Thanks!

**Comment by mishamyte** [comment]
Hi @MaximPopov,

A lot of excuses, my fail. Fixed in [v7.0.1](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/releases/tag/v7.0.1)

**Comment by MaximPopov** [comment]
Fantastic, thanks so much for super-fast turnaround! Everything is working well now.
