### ISSUE TITLE
Message with large property not sent (+ memory leak)

### ISSUE THREAD

**Issue by dagophil** [serilog-contrib/serilog-sinks-grafana-loki#51]
Hello,

when logging a message with a large property value (5000 characters), the message is not sent to grafana. Additionally, when logging such messages in a loop, the memory consumption of the application becomes higher and higher. Debugging with memory snapshots shows, that the object count of these objects increases forever:
- `Serilog.Events.ScalarValue`
- `Serilog.Events.Log`
- `Dictionary<String, Serilog.Events.LogEventPropertyValue>`

A log message with a string property with 1000 characters is sent correctly and without leak. A string property with 5000 characters (or more) produces the problem.

I attached an example project that reproduces the problem: [LargeLogMsg.zip](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/files/7059564/LargeLogMsg.zip)

The problematic part is:
```cs
var msg = new string('x', 5000);
while (true)
{
    Log.Logger.Information("Msg: {Message}.", msg);
    await Task.Delay(TimeSpan.FromSeconds(0.1));
}
```
When changing `msg` to `new string('x', 1000)`, the problem disappears.

Interestingly, the problem also disappears when logging the same message without using properties. This works fine:
```cs
Log.Logger.Information($"Msg: {msg}.");
```

Further information:
- Windows 10 (version 1909, build 18363.1679)
- Target framework `net5.0`
- Serilog.AspNetCore 4.1.0
- Serilog.Sinks.Grafana.Loki 7.0.1

Best regards, Philip

**Comment by mishamyte** [comment]
Hi @dagophil, 

For tracing troubles, caused to the logger it is recommended to use
```csharp 
SelfLog.Enable(Console.Error);
```

So after enabling SelfLog we could found an error in console log.
![Untitled](https://user-images.githubusercontent.com/5649656/131255855-3062886c-737f-4a9f-b218-908baf9a7750.png)

This error is produced by [loki](https://github.com/grafana/loki/blob/272a89c13df853a69ef50a53172ce5309c8f36a1/pkg/util/validation/validate.go#L38), limits are also [described](https://github.com/grafana/loki/blob/main/vendor/github.com/cortexproject/cortex/pkg/util/validation/limits.go).

**Default max length of a label value is 2048 symbols and could be overrided by [configuration](https://grafana.com/docs/loki/latest/configuration/)**

Hope, this information will be helpful for resolving your problem.

Also, I will resume the work to see what is the reason of memory leaks - this sink, Serilog or something else.

**Comment by dagophil** [comment]
Hello @mishamyte,

thank you for the quick diagnosis. I will change the limit in our loki configuration :)

I did not know about `SelfLog.Enable`, this will definitively help if other issues occur.

Best regards, Philip

**Comment by mishamyte** [comment]
OK, so the increase of a memory caused by queues. By default code uses two queues [source code](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/blob/master/src/Serilog.Sinks.Grafana.Loki/LokiSink.cs) - one for all incoming events from the Sink, and second one - is the batch, sending in the current iteration.

So we are facing the case when Loki rejects events and we are receiving `BadRequest` status code.
And in this case events, that were in `_waitingBatch` remains here (to be ensure that messages won't be lost) and  `_queue` increases over time. 

But in this case, events that are in `_waitingBatch` are invalid for Loki, so they won't be never delivered. And thei will block all following events.

As for me it is a big problem, so I will change the logic

**Comment by mishamyte** [comment]
Hi @dagophil,

Just released [v7.0.2](https://www.nuget.org/packages/Serilog.Sinks.Grafana.Loki/7.0.2) where entries, rejected by Loki are dropped from the queue. This helps sink to deliver next correct entries to Loki and fix a bottleneck with a memory.

Hope, you will find this useful!

**Comment by dagophil** [comment]
Hello @mishamyte,
thank you for the fix.
Regards, Philip

**Comment by mishamyte** [comment]
Hello @dagophil,

Could you, please, close the issue, if a problem is resolved?

Best regards,
Mykhailo

**Comment by dagophil** [comment]
Hello @mishamyte, currently, I'm on vacation. Is it okay if I check it on monday?

**Comment by mishamyte** [comment]
No worries, @dagophil)

I'm on vacation too, so no hurry)

Have a good vacation!

**Comment by dagophil** [comment]
Hello @mishamyte, I ran some tests and the leak seems to be gone :) Thank you for the fix!
