### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by JoeMarkov** [serilog-contrib/serilog-sinks-grafana-loki#63]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

v7.1.0

### Which version of .NET are you using?

net6.0

### Describe the bug

As a beginner of Loki/Serilog, when you start sending your logs to Loki, you easily get sample log entries like this one being sent to Loki:

```
{
  "streams": [
    {
      "stream": {
        "Protocol": "HTTP/1.1",
        "Method": "GET",
        "ContentType": "null",
        "ContentLength": "null",
        "Scheme": "https",
        "Host": "localhost:5001",
        "PathBase": "",
        "Path": "/HelloDotNet",
        "QueryString": "?FirstName=John\u0026LastName=Doe",
        "HostingRequestStartingLog": "Request starting HTTP/1.1 GET https://localhost:5001/HelloDotNet?FirstName=John\u0026LastName=Doe - -",
        "EventId": "{ Id: 1 }",
        "SourceContext": "Microsoft.AspNetCore.Hosting.Diagnostics",
        "RequestId": "0HMCRPRURRFP1:00000002",
        "RequestPath": "/HelloDotNet",
        "ConnectionId": "0HMCRPRURRFP1",
        "Application": "Client",
        "Environment": "Development"
      },
      "values": [ [ "1635616764470000000", "30-10-2021 19:59:24 [INF] [] [] Request starting HTTP/1.1 GET https://localhost:5001/HelloDotNet?FirstName=John\u0026LastName=Doe - -" ] ]
    }
}
...
```

However, by default we get way to many labels sent to Loki, that I assume will give us really bad performance.

I think it would be good if there was a config example provided with (from your experience) what labels should be sent for a typical ASP.NET Core service? 

Also, I think there should be a clear link added to https://grafana.com/docs/loki/latest/best-practices/ 

Or am I misunderstanding something how Loki and this sink works?

### To Reproduce

x

### Expected behavior

x

### Log/SelfLog output or exception with stacktrace

x

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by philosowaffle** [comment]
In a related note, I've really struggled with the [Application Settings](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Application-settings) documentation. I feel like each property warrants a description of exactly what it does.

Specifically, the interaction between `labels`, `filtrationMode`, and `filtrationLabels` is really unclear. I only figured out how to correctly use them after reading through closed issues to find examples of other peoples configs.

**Comment by JoeMarkov** [comment]
Feel free to post your config here, so we all can share knowledge.

Currently, the most confusing for me is when I use the **LokiJsonTextFormatter()**, the level is no longer part of the stream array below. Can I add it there? if so how?

```
      "stream": {
        "service": "webfrontend",
        "host": "server-1234",
        "environment": "production"
      },
```

If I do want to have the level as part of my stream, should it not be part of the array? of is it more bet practice to have it inside the JSON blob?

**Comment by mishamyte** [comment]
Pronto mates,

Thank your for your interest to this sink.

> However, by default we get way to many labels sent to Loki, that I assume will give us really bad performance.
> 
> I think it would be good if there was a config example provided with (from your experience) what labels should be sent for a typical ASP.NET Core service?
> 
> Also, I think there should be a clear link added to https://grafana.com/docs/loki/latest/best-practices/
> 
> Or am I misunderstanding something how Loki and this sink works?

We provide a high level of customization, so user could setup behavior for his needs. It is mean that user of sink is familiar with Loki (or at least compared logging systems and chose Loki consciously). But I agree, this part of doc should be extended.


> In a related note, I've really struggled with the [Application Settings](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Application-settings) documentation. I feel like each property warrants a description of exactly what it does.
> 
> Specifically, the interaction between `labels`, `filtrationMode`, and `filtrationLabels` is really unclear. I only figured out how to correctly use them after reading through closed issues to find examples of other peoples configs.

Thank you, for now you can use XML-doc of sink, which gives more info. But I will extend this section too.


> Feel free to post your config here, so we all can share knowledge.
> 
> Currently, the most confusing for me is when I use the **LokiJsonTextFormatter()**, the level is no longer part of the stream array below. Can I add it there? if so how?
> 
> ```
>       "stream": {
>         "service": "webfrontend",
>         "host": "server-1234",
>         "environment": "production"
>       },
> ```
> 
> If I do want to have the level as part of my stream, should it not be part of the array? of is it more bet practice to have it inside the JSON blob?

Correct, this behavior is by design. As described in doc
```xml
        /// <param name="createLevelLabel">
        /// Should level label be created. Default value is false
        /// The level label always won't be created while using <see cref="ILabelAwareTextFormatter"/>
        /// </param>
```
You could [see source code of LokiJsonTextFormatter](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/blob/master/src/Serilog.Sinks.Grafana.Loki/LokiJsonTextFormatter.cs#L94-L96). Level will be added as part of render and parsed correctly by Loki.

The discussion behind this decision could be found [here](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/pull/16#issuecomment-770374902)

**Comment by JoeMarkov** [comment]
A suggestion could be to add something like this to the documentation, that would clear up a lot of my confusion.

"From a querying (ie Grafana) point of view, it does not matter if the level tag is in the streams header block or inside the JSON blob".

**Comment by JoeMarkov** [comment]
Question

So, by default, out of the box, all of the various internal "labels" are added and sent to Loki, like these ones:

      "stream": {
        "Protocol": "HTTP/1.1",
        "Method": "GET",
        "ContentType": "null",
        "ContentLength": "null",
        "Scheme": "https",
        "Host": "localhost:5001",
        "PathBase": "",
        "Path": "/HelloDotNet",
        "QueryString": "?FirstName=John\u0026LastName=Doe",
        "HostingRequestStartingLog": "Request starting HTTP/1.1 GET https://localhost:5001/HelloDotNet?FirstName=John\u0026LastName=Doe - -",
        "EventId": "{ Id: 1 }",
        "SourceContext": "Microsoft.AspNetCore.Hosting.Diagnostics",
        "RequestId": "0HMCRPRURRFP1:00000002",
        "RequestPath": "/HelloDotNet",
        "ConnectionId": "0HMCRPRURRFP1",
        "Application": "Client",
        "Environment": "Development"
      },



I can of course use the filters, to get only the labels I want, that works, like:

      "stream": {
        "service": "webfrontend",
        "host": "server-1234",
        "environment": "production"
      },
      
Great! But how do I get selected or all of the removed "labels" into the JSON body or the log line? I might still want to get them sent to Loki, but not as a label of course...

**Comment by mishamyte** [comment]
I have a busy week. Will make doc changes when the free time would appear

**Comment by mishamyte** [comment]
Hello mates,

I have done some changes to the documentation:
* Extended [Application settings
](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Application-settings) section with a parameters description
* Added [Labels filtration](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Labels-filtration) page
* Added [Using LokiJsonTextFormatter and Grafana Loki json parser
](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Using-LokiJsonTextFormatter-and-Grafana-Loki-json-parser) page
* Added [Enterprise application configuration example](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Enterprise-application-configuration-example) page

And some minor adjustments.

Hope this would be useful for your experience with this sink
