### ISSUE TITLE
Question about how to get labels into the JSON body

### ISSUE THREAD

**Issue by JoeMarkov** [serilog-contrib/serilog-sinks-grafana-loki#65]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

latest

### Which version of .NET are you using?

net6

### Describe the bug

Question

So, by default, out of the box, all of the various internal "labels" are added and sent to Loki, like these ones:

 ```
 "stream": {
    "Protocol": "HTTP/1.1",
    "Method": "GET",
    "ContentType": "null",
    "ContentLength": "null",
    "Scheme": "https",
    "Host": "localhost:5001",
    "PathBase": "",
    "Path": "/HelloDotNet",
    "QueryString": "?FirstName=John\u0026LastName=Doe",
    "HostingRequestStartingLog": "Request starting HTTP/1.1 GET https://localhost:5001/HelloDotNet?FirstName=John\u0026LastName=Doe - -",
    "EventId": "{ Id: 1 }",
    "SourceContext": "Microsoft.AspNetCore.Hosting.Diagnostics",
    "RequestId": "0HMCRPRURRFP1:00000002",
    "RequestPath": "/HelloDotNet",
    "ConnectionId": "0HMCRPRURRFP1",
    "Application": "Client",
    "Environment": "Development"
  },
```

I can of course use the excluding filters, to get only the labels I want, that works, like:

```
  "stream": {
    "service": "webfrontend",
    "host": "server-1234",
    "environment": "production"
  },
```

Great! But how do I get selected or all of the removed "labels" into the JSON body or the log line? I might still want to get them sent to Loki, but not as a label of course...

### To Reproduce

none

### Expected behavior

none

### Log/SelfLog output or exception with stacktrace

none

### Additional context

none

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
You can't do it.

So you need to decide what metadata is important for you and include it in allowed list.
If you need to send it with a body, you could write custom formatter that will work with this properties.
It is described in [Serilog's Formatting Output section](https://github.com/serilog/serilog/wiki/Formatting-Output)

**Comment by JoeMarkov** [comment]
Oh, thanks for the explanation. 

Is this something that you plan to add to your Sink? Is my problem not a common use case/need?

I am new to Loki and I like the idea of using the Loki json parser in Grafana to be able to extract or filter on things like requestId or other json properties. As adding them as labels will make Loki much less performant.

As a new user its hard to know what current best-practice is when using .NET and Loki, do you have any good pointers that you can point me to or any open-source project on GitHub that uses your Sink?

**Comment by mishamyte** [comment]
No, this is not the thing which would be implemented.

Cause it is the main idea of structured logging - to take an application log that is delivered as a string of text and convert it into a simple relational data set that can be more easily searched and analyzed.

So in this case you have a message (kinda rendered message, pushed for example in `logger.Write*()` methods) and metadata - all this log event properties that are used for indexing in log systems.

We have used Loki with this sink in one system with 20+ microservices. So we have defined the critical properties (like RequestId and etc) and whitelisted them. And it was kinda efficient to deliver and query logs. I can't say which properties you should keep (cause it is all about your business needs), but it could be clever to keep kinda RequestId to to a tracing.

So yep, specific of Loki's index defines kinda new approach to work with logs.

About projects - I haven't searched GH in case of them, so no info for now.

Maybe @AnderssonPeter, author of `LokiJsonTextFormatter` could share some useful info?

**Comment by JoeMarkov** [comment]
Ah, you are right! I just need to get those log context properties into the output template somehow.
Thanks for getting me on the right track.

Anyway, it would be awesome (when you have time time) if you could share how to use and configure your sink in production!

**Comment by mishamyte** [comment]
@JoeMarkov it could be tricky, cause you have two ways:

- Manually push properties into log message
- Implement custom formatter

And you could face the case when your messages are oversaturated by the info, that would cause readability decreasing 

Finally we have switched to Seq (but it was political decision in the company), but I will post an example of configuration tomorrow, I hope

**Comment by tndata** [comment]
Oh, I have tried Seq and its nice! For my usecase I like to use Grafana and there does not seem to find any Seq data source for Grafana.

Thanks for the warnings, I will do some experimenting with your Sink and Loki. I guess doing a custom formatter is the way to go.

**Comment by mishamyte** [comment]
There is no need to delete a messages ))

So, as promised, this is an example of config from one of ours services (dev env to minimum levels could be strange). I little cleaned up and added few new config keys to satisfy v7.1.0 configuration:

```json
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Console",
      "Serilog.Sinks.Grafana.Loki"
    ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Information",
        "Microsoft.EntityFrameworkCore": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "{Timestamp:dd-MM-yyyy HH:mm:ss} [{Level:u3}] {Message}{NewLine}{Exception}"
        }
      },
      {
        "Name": "GrafanaLoki",
        "Args": {
          "uri": "http://loki:3100", // Your url
          "labels": [
            {
              "key": "app",
              "value": "service-name" // Label with service name
            }
          ],
          "filtrationMode": "Include",
          "filtrationLabels": [
            "ActionName", // ASP.NET Core
            "commandText", // EF Core
            "elapsed", // EF Core
            "ElapsedMilliseconds", // ASP.NET Core
            "FailureMessage", // ASP.NET Core
            "parameters", // EF Core
            "RequestId",  // ASP.NET Core
            "SourceContext", // .NET Core
            "StatusCode", // ASP.NET Core
            "X-Trace-Id" // Custom header for tracing (we didn't used Jaeger or etc that time)
          ],
          "outputTemplate": "[{Time}] {Message}{NewLine}{Exception}",
          "createLevelLabel": true,
          "useInternalTimestamp": true
        }
      }
    ]
  }
}

```

**Comment by JoeMarkov** [comment]
awesome Thanks! You are a life saver! :-)

**Comment by mishamyte** [comment]
In our case it worked well. It was default labels setup for typical service. And some services (like Identity or Ocelot (reverse proxy)) has an additional ones

But in my opinion, you should try it from the perspective of your business needs and system configuration))

**Comment by mishamyte** [comment]
Sorry, mate. I have asked guys from my team. This was the early config and later we have filtered it to improve performance after load has increased (I was on holiday that time).

Final was:
```json
          "filtrationLabels": [
            "ActionName", // ASP.NET Core
            "RequestId",  // ASP.NET Core
            "SourceContext", // .NET Core
            "StatusCode", // ASP.NET Core
          ]
```

The reason was that a load have increased dynamic ones (like elapsed etc) and Loki started struggling

**Comment by mishamyte** [comment]
And let me do some things clear with a `Serilog.Sinks.Grafana.Loki.SampleWebApp` sample. 

For example, we have a standard web application with a next configuration:
```json
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Console",
      "Serilog.Sinks.Grafana.Loki"
    ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "Enrich": [
      "WithThreadId"
    ],
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "{Timestamp:dd-MM-yyyy HH:mm:ss} [{Level:u3}] [{ThreadId}] {Message}{NewLine}{Exception}"
        }
      },
      {
        "Name": "GrafanaLoki",
        "Args": {
          "uri": "http://localhost:3100",
          "textFormatter": "Serilog.Sinks.Grafana.Loki.LokiJsonTextFormatter, Serilog.Sinks.Grafana.Loki",
          "labels": [
            {
              "key": "app",
              "value": "web_app"
            }
          ],
          "filtrationMode": "Include",
          "filtrationLabels": [
            "app"
          ],
          "outputTemplate": "{Timestamp:dd-MM-yyyy HH:mm:ss} [{Level:u3}] [{ThreadId}] {Message}{NewLine}{Exception}",
          "createLevelLabel": true,
          "useInternalTimestamp": true
        }
      }
    ]
  }
}
```

Simple logging method is
```csharp
        [HttpGet("info")]
        public IActionResult GetInfo()
        {
            var odin = new {Id = 1, Name = "Odin"};
            _logger.LogInformation("God of the day {@God}", odin);
            return Ok(odin);
        }
```

In this case, using next filter
```codeql
{app="web_app"}
``` 
we could see
![1](https://user-images.githubusercontent.com/5649656/140620823-0deaac1f-5e9f-4a27-a12a-5e2bf9d5bba4.PNG)

In this case you see metadata as a detected fields. This is cool, but not useful for querying. 

So the next step is to add a `json` parser, which will turn our detected fields into _query time labels._

```codeql
{app="web_app"} | json
```
Our message will be destructured into:
![2](https://user-images.githubusercontent.com/5649656/140620957-2d540d70-8a94-4496-b072-e10cb20afaa2.PNG)
(I'm sorry for screen size, I'm from laptop now)

And the next step will be adding the filter:
```codeql
{app="web_app"} | json | ConnectionId="0HMD1AQG310G0"
```

And your result will be filtered by criteria.

---
So, I hope this explanation will be useful for you.
Also excuses for some missinformation in previous messages, I forgot some details over time and rechecked it now

**Comment by JoeMarkov** [comment]
Thanks your awesome answer here, it clarified my last misunderstandings!

Would we awesome if this could be incorporated in the documentation! thanks!

**Comment by mishamyte** [comment]
In progress right now)

**Comment by mishamyte** [comment]
Documented in [Using LokiJsonTextFormatter and Grafana Loki json parser
](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Using-LokiJsonTextFormatter-and-Grafana-Loki-json-parser)
