### ISSUE TITLE
Unable to get serilog to log to grafana cloud

### ISSUE THREAD

**Issue by sirhamsteralot** [serilog-contrib/serilog-sinks-grafana-loki#66]
I'm trying to get serilog to log to grafana cloud loki except I cannot get this to work and feel like I have reached the end of things to try.
Scraping logs and sending them to grafana cloud via the grafana-agent is working so i assume the same credentials (or credentials with the same permissions)  should work here aswell.

My application config json is as follows:
```
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Grafana.Loki"
    ],
    "MinimumLevel": {
      "Default": "Debug"
    },
    "Enrich": [ "FromLogContext" ],
    "WriteTo": [
      {
        "Name": "GrafanaLoki",
        "Args": {
          "uri": "https://logs-prod-eu-west-0.grafana.net/api/prom/push",
          "credentials": {
            "Login": "User",
            "Password": "API key"
          },
          "labels": [
            {
              "key": "app",
              "value": "somevalue"
            }
          ],
          "outputTemplate": "{Timestamp:dd-MM-yyyy HH:mm:ss} level={Level} | {Message}{NewLine}{Exception}"
        }
      }
    ]
  }
}
```

**Comment by mishamyte** [comment]
Hello @sirhamsteralot,

You should use root loki uri. In your case it is `https://logs-prod-eu-west-0.grafana.net`

**Comment by sirhamsteralot** [comment]
That worked, I knew it was probably something like that I was missing but I couldnt find it anywhere, 😅  thank you
