### ISSUE TITLE
Issue with Logs showing up in Grafana/Loki - maybe?

### ISSUE THREAD

**Issue by tehmufifnman** [serilog-contrib/serilog-sinks-grafana-loki#72]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

v7.1.0

### Which version of .NET are you using?

net6.0

### Describe the bug

I have a service that is running on 4 nodes, all of which log to Loki.
The service has big spikes in activity every 2 hours for around 10min, and then very low activity in the interim.
The interim logs basically just have 2-3 logs about the data I am trying to processes not being updated yet. 
The latest logs are several hours old.

For the sake of discussion, lets say my last log in Loki is showing received at 9am.

What I am seeing is that during these periods of low activity, I am not seeing any new logs show up when I query Loki.
That said, if I wait awhile and run my query again - I do see MORE logs show up, but they're still old.
Referencing the above time, ill see some more come in at 9:01am, 9:02am, etc...

Its almost as of "new" logs being queued are finally pushing old ones all the way to Loki.

I am relatively new to using Loki, and DEFINITELY new to using Loki through .NET.

Any clue what could be going on?

I've looked at the common problems, and it "feels" like I might have an issue with my config - but I am generally not understanding what impact each of the various configuration options have (such as batchPostingLimit, period, etc...)

### To Reproduce

This is my configuration:
```
        Log.Logger = new LoggerConfiguration()
            .Enrich.FromLogContext()
            .Enrich.WithProperty("MachineName", Environment.MachineName)
            .MinimumLevel.Information()
            .WriteTo.Console(new MessageTemplateTextFormatter("{Timestamp:dd-MM-yyyy HH:mm:ss} [{Level:u3}] [{ThreadId}] {Message}{NewLine}{Exception}"))
            .WriteTo.GrafanaLoki(
                "https://logs-prod-us-central1.grafana.net",
                credentials: new LokiCredentials
                {
                    Login = "MY_LOGIN",
                    Password = "MY_PASSWORD"
                },
                labels: new List<LokiLabel>
                {
                    new() {Key = "job", Value = jobName},
                    new() {Key = "source", Value = "csharp_backend"}
                },
                textFormatter: new LokiJsonTextFormatter(),
                outputTemplate: "{Timestamp:dd-MM-yyyy HH:mm:ss} [{Level:u3}] [{ThreadId}] {Message}{NewLine}{Exception}"
            )
            .CreateLogger();
```

### Expected behavior

I expect to see logs in real-time - I assume I have something configured wrong?

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
Hi @tehmufifnman,

If I got you correctly, there are no log loss, but the is a delay?
And could you, please, say me what is the delay in time?

Cause the log sending timer is triggered every 1 second (by default) and seems like a need a little bit more info to determine where the issue is.

Could it be caused by network latency?

**Comment by mishamyte** [comment]
Also do you run the same service on different replicas?

In this case the situation with log entry dropping could have place.
I strongly recommend enable `SelfLog` (as described in doc) and monitor stdout of service for some sink info.

And as a rescue I could recommend add some label with `NodeId`, something unique for node instance (this will help Loki process correctly).

And not in case of your question, but I strongly recommend to read the [Labels filtration section
](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Labels-filtration), cause in the future, you could face an issues with performance

**Comment by tehmufifnman** [comment]
Hello!

Yes it is delayed - but for HOURS... its weird - my services go through a period of very low activity (but still should be some logs every few minutes or so).  When activity kicks back up, I start to see logs from 3 hours ago start to slowing show up.

Its almost like the node is holding on to logs until a certain number of logs to transmit to Lok is reached.

**Comment by mishamyte** [comment]
I haven't heard about behavior like this.

So could you please enable SelfLog and monitor is also?

**Comment by mishamyte** [comment]
Hi @tehmufifnman!

Any updates to this?

**Comment by yakob-aleksandrovich** [comment]
I might have an issue along the same lines. Data is succesfully being inserted, as far as I can see, but it seems to take a while for the data to show up. 
I'm still in testing mode. Just sending a couple of log lines to the API (localhost:3100). Labels are already available, as demonstrated in `logcli query labels`, but somehow the data is not showing. Only after some time (half an hour?), the data shows up, through `logcli` or `grafana Explorer.`

**Comment by mishamyte** [comment]
@yakob-aleksandrovich do you have a single app instance or multiple ones? What version of Loki do you use?

**Comment by yakob-aleksandrovich** [comment]
@mishamyte Sorry, I just realize that my issue is not related to serilog, but to Loki. Sorry for your time...

**Comment by mishamyte** [comment]
OK, but thank you for the information about data arriving

**Comment by mishamyte** [comment]
Seems like we have no info, closed
