### ISSUE TITLE
Documentation on createLevelLabel is confusing

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [serilog-contrib/serilog-sinks-grafana-loki#74]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

v7.1.0

### Which version of .NET are you using?

net6.0

### Describe the bug

The docs here:
- https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Application-settings
- https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Visualizing-log-level-in-Grafana

clearly state that:
> *The level label always won't be created while using ILabelAwareTextFormatter*
Which includes the `LokiJsonTextFormatter`.

But why is the example appsettings in https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Using-LokiJsonTextFormatter-and-Grafana-Loki-json-parser 

using both

```json
"textFormatter": "Serilog.Sinks.Grafana.Loki.LokiJsonTextFormatter, Serilog.Sinks.Grafana.Loki",
```

and

```json
"createLevelLabel": true,
```

if `createLevelLabel` is ignored in this case? 

I tried variations using `createLevelLabel` in combination with `filtrationLabels` etc. but `createLevelLabel` does not seem to have an effect when using `LokiJsonTextFormatter` ?

While the JSON parsing (using `| json ` in Grafana is working as described, I would like to have `level` as a real Loki Label (for usage in stream selector because it is easier to type), as it was pre 7.0,

But I guess this is not possible in any way?

### To Reproduce

Use the configuration in https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Using-LokiJsonTextFormatter-and-Grafana-Loki-json-parser 
including

```json
"labels": [
    {
        "key": "app",
        "value": "web_app"
    }
],
"filtrationMode": "Include",
"filtrationLabels": [
    "app"
],
"outputTemplate": "{Timestamp:dd-MM-yyyy HH:mm:ss} [{Level:u3}] [{ThreadId}] {Message}{NewLine}{Exception}",
"createLevelLabel": true,
```

A loki label `level` is never created (as per design?)

### Expected behavior

There should be some way to restore the behavior from pre 7.0 to get a real loki level label?
We MUST use the JSON formatter because of cardinality and to keep the log properties.

### Additional context

Also, does `outputTemplate` do anything when using `LokiJsonTextFormatter` ? It did not look like it but maybe I got confused.

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by Mario-Hofstaetter** [comment]
I remembered I've already kind of answered this myself in https://github.com/serilog-contrib/serilog-sinks-grafana-loki/pull/16#issuecomment-774980316 

So if I use
```json
          "createLevelLabel": true,
          "filtrationMode": "Include",
          "textFormatter": "Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact",
```

I'm back to the desired behavior. What's not clear for me @mishamyte :

- What is the advantage of using `LokiJsonTextFormatter` in contrast to e.g. `RenderedCompactJsonFormatter` ? What features does it have that `RenderedCompactJsonFormatter` or `CompactJsonFormatter` does not ?

**Comment by mishamyte** [comment]
Hi @Mario-Hofstaetter,

The discussion was [here](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/pull/16#issuecomment-770455309).

After that I have received a lot of appeals about this implicit behavior. So I decided to change it v7.0.
It is mean that if you are using json-based formatter, you also use `json` pipeline in Loki. 
This leads to smaller count of labels.

---
> But why is the example appsettings in https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Using-LokiJsonTextFormatter-and-Grafana-Loki-json-parser
> 
> using both
> 
> ```json
> "textFormatter": "Serilog.Sinks.Grafana.Loki.LokiJsonTextFormatter, Serilog.Sinks.Grafana.Loki",
> ```
> 
> and
> 
> ```json
> "createLevelLabel": true,
> ```

Thank you, it's a typo (first there was simple formatter). Will fix it.

---
> * What is the advantage of using `LokiJsonTextFormatter` in contrast to e.g. `RenderedCompactJsonFormatter` ? What features does it have that `RenderedCompactJsonFormatter` or `CompactJsonFormatter` does not ?

You could compare all named formatters, using their source code:
- [LokiJsonTextFormatter](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/blob/master/src/Serilog.Sinks.Grafana.Loki/LokiJsonTextFormatter.cs)
- [RenderedCompactJsonFormatter](https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/RenderedCompactJsonFormatter.cs)
