### ISSUE TITLE
Unify labels behavior to simplify understanding (redesign log level data)

### ISSUE THREAD

**Issue by mishamyte** [serilog-contrib/serilog-sinks-grafana-loki#76]
Now there are some "magical" behavior of sink. We have `createLevelLabel` parameter and also `ILabelAwareTextFormatter` that provides us a different behavior, which overlaps each other.

- [x] Check if level passed by Serilog by default as a part of event data
- [x] Check how it is created/processed in standard & json sink
- [x] Check is it respected by filtration
- [x] Fix code + tests
- [x] #102
- [x] Check if `level` would be used as a property name

**Comment by EraYaN** [comment]
Also would be great if we could set the internal property names like "Message" etc. So we could for example match the Serilog.Formatting.Compact formatters.

**Comment by mishamyte** [comment]
> Also would be great if we could set the internal property names like "Message" etc. So we could for example match the Serilog.Formatting.Compact formatters.

@EraYaN I don't think this is a way we should follow. 
From my perspective, `ITextFormatter` is a pluggable part that could be customized by user for his needs. It is not a good way to add to the root configuration properties, related to it.

If you need to have a custom internal property names - you could provide your own implementation of formatter and set it up into this sink.

By in the concrete case, if you think that described formatter would be used for a lot of people - feel free to add an enhancement discussion.
