### ISSUE TITLE
Label filters

### ISSUE THREAD

**Issue by X-7r3em** [serilog-contrib/serilog-sinks-grafana-loki#78]
Hello.
Today I had this issue. At work, we are using a label(from Loki) (property from ILogger) for each request. Its easy, and all other sings work perfectly with it. However, as each Id is unique, we take up all the loki streams. And this is not good.

I would like to keep the properties with the interface of ILogger used throughout the code as all other sinks work properly, but would like to be able to tell the GrafanaLoki that for example TraceId property should not be a grafana label, rather, it should be appended to the message. This way, I sill keep the functionality of the ILogger, and have the performance of the Loki. For example, it is done in Serilog.Sinks.Loki - https://github.com/JosephWoodward/Serilog-Sinks-Loki/blob/master/src/Serilog.Sinks.Loki/LokiBatchFormatter.cs#L147

Is there a similar option that I may be missing? I saw the filter include and exclude options and the list of labels, however, the code, first excludes the properties and then formats the message, and I get a blank for TraceId for example. I would like the message to be formatted and then the labels to be excluded. And I think a lot of production heavy use code will benefit from this. :)

**Comment by mishamyte** [comment]
Hi @X-7r3em,

Thank you for your suggestion. For now there is no possibility to implement this behavior. 
I could recommend you to look at [Using LokiJsonTextFormatter and Grafana Loki json parser
](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Using-LokiJsonTextFormatter-and-Grafana-Loki-json-parser). It could help you to keep a low cardinality, but also use json parser of Loki and perform some search via extracted labels.
_______
Also we can discuss how described by you behavior could live in current ecosystem of `Serilog.Sinks.Grafana.Loki` and implement it in v8 release

**Comment by X-7r3em** [comment]
Hi @mishamyte ,

Thank you for the response. So here is what I would like to achieve.

I know that I can write _logger.LogInformation(string.Format("Some random message with {TraceId}", traceId));
This way, there is no TraceId label and I have it in the message. However, whenever I need to do a call to _logger, I need to get the traceId from somewhere, meaning, DI or something else, and this just bloats the code.

What I achieved is, to create a Scoped Property (TraceId) for each request, meaning, wherever in my code I can call the following:
_logger.LogInformation("Some random message with {TraceId}")

Now first of all, I do not need to worry that I needed to inject it, second, its far clearer, and third - only the library is going to format the message once, instead of it being formatted twice.

And If I filter the TraceId I get a wrong log message. It would be awesome, if the message is formatted, and then the labels are removed. For example giving us more modes in LokiLabelFiltrationMode and a bit of tweaking in LokiBatchFormatter and would make it possible. Just throwing ideas out there for the moment

**Comment by mishamyte** [comment]
In your case, do you wanna use `TraceId` as something, that could be useful for filtering. Or is it just the part of the message without any meaning in terms of structured logging?

And what about my proposal? Could it help you?

I don't remember (need to check) could the logging property from scope be used in message template in your way

**Comment by X-7r3em** [comment]
Yes, the TraceId is very useful (not sure if entirely for structured logging, but I will explain). By it we trace each request. We can use it either by {TraceId="someid"} as a label, or for example {environment="dev") |= "someId". This way, If I need to trace all the logs for one request, I get it by one of the two ways, as the TraceId is unique per request. In the first option, its a label and this kills Loki, literally. In the second, it is just a part of the message, however, it still does a perfect job in my use case, as I can get the logs for the request.

Thank you for your solution. I know that this kind of idea will work, however, I will need to inject the TraceId everywhere, which is a lot of pollution of my code.

Right now, what I do for the trace id is 
_logger.BeginScope(new Dictionary<string, object> { ["TraceId"] = "InjectedTraceId only in this method" }))
{
}

And form there on, I have the TraceId everywhere in my scope in the ASP Net Core app. And I can call _logger.LogInformation("Some random stuff{TraceId}"); and It works like a charm :)

Your proposal requires me to inject the TraceId wherever I call the _logger, not only at one place, so that is what I do not like about it. As code grows, it will get harder to maintain.

**Comment by mishamyte** [comment]
Yes, so it terms of structured logging`TraceId` will be valuable for you

Sorry, I think we have a misscommunication. 

My solution is about how data is delivered to Loki and handled by it. It does not tell you how to deal with `TraceId` in you code. So you could continue to use it how you want.

Have you read the link, that I shared? Maybe, you need some demo-solution to see how it could be done?

**Comment by X-7r3em** [comment]
Yes, I read the link, but it does not help me in my use case. It is as you said, associated to the way the data is represented. For example, I still need to add the odin/traceId object ->
var odin = new {Id = 1, Name = "Odin"};
_logger.LogInformation("God of the day {@God}", odin);

And If I have a second controller, in another class, I need to add the odin object again. If I add it as with a _logger.BeginScope, I do not need to have access to the odin object anywhere else

**Comment by mishamyte** [comment]
I'm checking right now.

So, it I got you right, logging line will have access to `MyTraceId`?

```csharp
            using (_logger.BeginScope(new Dictionary<string, object> { ["MyTraceId"] = Guid.NewGuid()}))
            {
                _logger.LogInformation("I am with {MyTraceId}");
            }
```

**Comment by mishamyte** [comment]
OK, so I have tested. 

I used the current revision (`master`) and have modified two files:
https://gist.github.com/mishamyte/aaf8b7923ff84288f13812ad0716d025

In this case we could see that filter excludes all labels (for the clearance of demo) and scope is created in `Demo` method of `SerilogController`

We could see that there are no additional labels created (selector: `{app="web_app"}`)
![image](https://user-images.githubusercontent.com/5649656/149396713-e639dd41-e813-4c2b-bc43-dbf33b2477e5.png)

But if we will add `json` parser this label is parsed and could be used in `LogQL` queries

![image](https://user-images.githubusercontent.com/5649656/149396905-e3040b7c-d06c-47d0-bb7d-dc3de15212de.png)
_____
I have removed `using` and it works too! (but short-living log scopes it is recommendation from MS)

**Comment by mishamyte** [comment]
So does it look at solution for your case?

1. You decrease log cardinality (cause `TraceId` is not a label)
2. You have possibility to use it in queries (cause it is parsed by Grafana)
3. You could use logs scopes, as you have used before (actually I did not touch this part)

**Comment by X-7r3em** [comment]
No, unfortunately, still not the solution needed. Because in your example, the scope lives only in demo method. I want the scope to live for the whole Scoped HTTP request (And I dont care what MS recommended. If they made ILogger a bit more extensible, I would have extended it and forgotten about this a long time ago, but eh, SOLID principles are for looses). This way, I have the scope for each log in the Controller method, in any service method called by the controller, in all the filters for that request. If the scope ends in the controller, I will get a new TraceId the next time I request it in a service or a filter.

 The whole idea is, if I have a request 123-AF-3 for example, if I want all the logs it made, I can do it with a single filter.

**Comment by mishamyte** [comment]
I do not see any problem, but let's move forward.

Could you please spend a little time and make a demo app and I will try to look for a way to do it gracefully. Also you could show how it could be done with JosephWoodward's sink

**Comment by X-7r3em** [comment]
Yep, I will give you a demo app with the Begin Scope at work, and I will show you where it would be nice to have the new configuration :)

**Comment by mishamyte** [comment]
Thank you, @X-7r3em!

I appreciate that

**Comment by X-7r3em** [comment]
Hi :) 
https://github.com/X-7r3em/SerilogDemo here is the example of what we are doing, and there are comments why its happening.
We cloned the code and found a solution on it, I will make a pull request, but the guys maintaining the code are free to change it, or we can discuss how it can be done better for the sink itself. Because right now, we did it for ourselves, with 3 lines of code, a quick and nice fix, but there may be other cases, and for it to be done right, a discussion would be nice.

**Comment by X-7r3em** [comment]
@mishamyte So, I have to apologize, it seems that the LokiJsonTextFormatter will do the trick, as it works with filtrationLabels and filtrationMode, it separates the loki labels, but still has the message displayed properly. The only thing is, that you may have to get used to seeing messages in a json, instead of a normal line, but eh.

Still, my previous proposal still stands. My basic solution is:
in new LokiBatchFormatter() -> in the Format method -> Something in the lines of:
IDictionary<string, string>? labels = group.Key;
var stream = batch.CreateStream();

foreach (var label in labels)
{
    if (_explicitLokiLabels != null && !_explicitLokiLabels.Contains(label.Key))
    {
        continue;
    } 
    stream.AddLabel(label.Key, label.Value);
}

**Comment by mishamyte** [comment]
Hi @X-7r3em,

I'm glad that it works for your case)

> @mishamyte So, I have to apologize, it seems that the LokiJsonTextFormatter will do the trick, as it works with filtrationLabels and filtrationMode, it separates the loki labels, but still has the message displayed properly. The only thing is, that you may have to get used to seeing messages in a json, instead of a normal line, but eh.

I think it could be solved by Grafana's instruments too. 

You could click to an eye icon near detected field and this field would be displayed (is could be multiple fields, yeah)
![1](https://user-images.githubusercontent.com/5649656/149665002-abd5b62f-9951-48e0-b792-061e02835321.PNG)
![2](https://user-images.githubusercontent.com/5649656/149665010-8803c1b6-0864-4ed8-9f28-a71ef4fd5ae0.PNG)

It is experience similar to E(L/F)K stack and usage of Kibana

> Still, my previous proposal still stands. My basic solution is: in new LokiBatchFormatter() -> in the Format method -> Something in the lines of: IDictionary<string, string>? labels = group.Key; var stream = batch.CreateStream();
> 
> foreach (var label in labels) { if (_explicitLokiLabels != null && !_explicitLokiLabels.Contains(label.Key)) { continue; } stream.AddLabel(label.Key, label.Value); }

Thank you, I will add it to the backlog and will investigate how to make it similar for all formatters. 
Cause as described in #79, we will make a breaking change in v8 and a JsonFormatter will be default one. I wanna make a similar experience and avoid a different combinations of flags/etc

**Comment by X-7r3em** [comment]
@mishamyte Thank you :) I feel like we can close this one :)
