### ISSUE TITLE
Use LokiJsonTextFormatter as default formatter

### ISSUE THREAD

**Issue by mishamyte** [serilog-contrib/serilog-sinks-grafana-loki#79]
According to features of Loki 2.0 (json parser) and setting up things, it is preferred to use `LokiJsonTextFormatter`, cause it provides more flexibility and make harder to "shoot yourself in the leg"

**Comment by AntonPetrov83** [comment]
I would suggest to use Serilog.Logfmt as a default formatter because logfmt is more traditional format for Loki and it's more human-friendly than JSON and Loki UI is for humans.
