### ISSUE TITLE
No Loki metadata parsing with LokiJsonTextFormatter 

### ISSUE THREAD

**Issue by Depechie** [serilog-contrib/serilog-sinks-grafana-loki#96]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

v7.1.0

### Which version of .NET are you using?

net6.0

### Describe the bug

When looking at the sample configuration defined here : https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Using-LokiJsonTextFormatter-and-Grafana-Loki-json-parser the sample screen of Loki will show almost all metadata as detected fields.

When I try my output template configuration, almost no fields are detected.
Because of that, I'm now unable to link a field as internal link for Tempo from Loki logs.

My current config is as follows:
```
      {
        "Name": "GrafanaLoki",
        "Args": {
          "uri": "http://localhost:3100",
          "textFormatter": "Serilog.Sinks.Grafana.Loki.LokiJsonTextFormatter, Serilog.Sinks.Grafana.Loki",
          "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff}] [{Level}] [{SourceContext}] [{SpanId}] [{TraceId}] {Message:lj}{NewLine}{Exception}"
        }
      }
```

And I would like to link the SpanId with Tempo, but not sure how to get it so that Loki picks it up as a detected field.

Only way to get it working, is to revert to the regular non json textformatter and use an output template like:
`"outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff}] [{Level}] [{SourceContext}] [{SpanId}] TraceId={TraceId} {Message:lj}{NewLine}{Exception}"`
So that I then can use the Derived Fields feature on the Loki data source in grafana to search through a regex on **TraceId=**. [https://grafana.com/docs/grafana/latest/datasources/loki/#derived-fields](https://grafana.com/docs/grafana/latest/datasources/loki/#derived-fields)

But of course I would rather use the JSON formatter.

Any tips?

### To Reproduce

https://github.com/Depechie/OpenTelemetryGrafana

### Expected behavior

Would hope to get detected fields for spanid and traceid.

### Application or code sample, which could be used to reproduce a bug

https://github.com/Depechie/OpenTelemetryGrafana

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
Hi @Depechie, 

I don't see any problems with labels detecting, but I see that you didn't added a static label, which could be used for querying (you can't use `| json` pipeline without filter).

So I have downloaded your repo and changed config a little (added a static level and added filtering to ensure that none of properties except static won't be added)
```json
      {
        "Name": "GrafanaLoki",
        "Args": {
          "uri": "http://localhost:3100",
          "textFormatter": "Serilog.Sinks.Grafana.Loki.LokiJsonTextFormatter, Serilog.Sinks.Grafana.Loki",
          "labels": [
            {
              "key": "app",
              "value": "web_app"
            }
          ],
          "filtrationMode": "Include",
          "filtrationLabels": [
            "app"
          ],
          "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff}] [{Level}] [{SourceContext}] [{SpanId}] [{TraceId}] {Message:lj}{NewLine}{Exception}"
        }
      }
```

And how I could do a query across Grafana - `{app="web_app"} | json` and next data is parsed by Loki:
![image](https://user-images.githubusercontent.com/5649656/159791317-81ceef8c-3e95-4907-91c8-e323bc22e311.png)

So seems like all works as designed.

I could suggest that you had been confused by next screen:
![image](https://user-images.githubusercontent.com/5649656/159791482-b0ece2a0-dbf2-41a9-9c96-f6e733f025bf.png)

Here are labels, which are appended to Loki as plain labels and not parsed. You need a `json` pipe to extract data. I strongly advice to give a look at this [article]https://grafana.com/blog/2020/10/28/loki-2.0-released-transform-logs-as-youre-querying-them-and-set-up-alerts-within-loki/), where described the way to work with this pipe

**Comment by Depechie** [comment]
@mishamyte thx for the nice detailed info! I will take a look at the given documentation!

**Comment by mishamyte** [comment]
@Depechie hope it would help. Feel free to ask any questions if needed

**Comment by Depechie** [comment]
Maybe while we are at it, did you already try to use the derived fields feature to link the trace id to tempo? While using your | json query?

**Comment by mishamyte** [comment]
No, we are using other system for tracing, but I will give a look how it could interact

**Comment by mishamyte** [comment]
@Depechie could be useful next link: [Kubernetes Observability Using Loki, Cortex, Tempo and Grafana](https://invisibl.io/blog/kubernetes-observability-loki-cortex-tempo-prometheus-grafana/). Author uses autodetected labels

**Comment by Depechie** [comment]
Ha found it!!
In the grafana datasources provisioning file I need to set

**matcherRegex: "\u0022TraceId\u0022:\u0022(\\w+)\u0022"**

for the Loki derived field to link to Tempo while using your JSON config for log entries.
Thx again for the help.
